### ISSUE TITLE
feat-admin-dashboard-all

### ISSUE THREAD

**Issue by ram9611** [BeeLinkers/EngleBee#14]
### ✨ 구현할 기능

- 관리자 dashboard 만들기
- 유저 태그별 분포 차트를 볼 수 있습니다
- 일일 수업 개설 횟수를 볼 수 있습니다
- 나이대별 학생 분포 수를 볼 수 있습니다
- 날짜별 LLM API 호출 수 통계를 볼 수 있습니다.

### ✅ TODO

- [ ] dashboard 이동시 ajax 통신으로 서버에 data 요청하기
- [ ] 차트를 만들기 위한 data를 DB에서 가져오기
- [ ] 가져온 data를 타임리프에 차트로 만들기
