### ISSUE TITLE
feat-infra-session-db-setting

### ISSUE THREAD

**Issue by junslog** [BeeLinkers/EngleBee#25]
### ✨ 구현할 기능

- 현재 인프라 구성에서는 
CI/CD 파이프라인을 통해 배포가 이루어지거나, 
어플리케이션을 종료하고 다시 시작될 때 현재 로그인된 유저의 세션이 모두 사라집니다.

- 이는 세션을 스프링 부트 어플리케이션의 내장 톰캣의 메모리 영역에 저장되기 때문입니다.

- 또한, 추후 서비스가 확장하고 여러 대의 SpringBoot 컨테이너를 통해 운영하게 될 때,
각 어플리케이션(컨테이너)별로 세션을 관리하기에, 세션을 동기화해야할 필요가 있습니다.

- 세션의 동기화를 위해서는 어플리케이션 내부에서 세션을 관리하는 것이 아니라, 외부 저장소에 세션을 저장하는 방법이 있습니다.
이 중에서도 RDS의 MariaDB에 세션 테이블을 만들어 쓰는 방법 
/ ElastiCache ( Redis, Memcached )와 같은 메모리 DB를 세션 저장소로 사용할 수 있습니다.

- 우리 서비스는 배포 초기 단계이고, 사용자가 많지 않아 성능 이슈가 크지 않은 점
ElastiCache의 비용 문제 / 설정의 간편함을 통한 빠른 MVP 작성을 고려하여
RDS의 MariaDB에 세션 테이블을 두어 세션을 저장하고 조회하는 방식으로 구현하겠습니다.

### ✅ TODO

- [x] 로컬 개발환경에서 세션 DB를 사용하도록 설정하는 의존성을 추가합니다.
- [x] h2 console을 통해 세션 테이블이 제대로 만들어지는지 확인합니다.
- [x] EC2를 통해 RDS에 접속하여 세션 테이블을 만들어줍니다.
- [x] develop 브랜치로 머지하여, CICD 파이프라인을 통해 의존성 및 설정 변경사항을 EC2 컨테이너에 반영합니다.
