### ISSUE TITLE
refactor-general-videochat-api

### ISSUE THREAD

**Issue by ram9611** [BeeLinkers/EngleBee#29]
### ✨ 리팩토링할 기능

- 배포 환경에서도 화상 과외, 텍스트 채팅 정상 작동 확인
- 화상 채팅 종료시 lecture status 변경 및 exam 생성

### ✅ TODO

- [ ] 시그널링 서버 주소 변경
- [ ] 채팅 구현 확인
- [ ] 필요하다면 시큐리티 설정 변경
- [ ] chatPageController를 통해 수업 id 전달받고, 뷰에 추가하기
- [ ] 종료 버튼 클릭시 수업ID를 이용하여 수업 status 변경
- [ ] 수업 ID를 이용하여 시험 생성
- [ ] 메인페이지로 이동
