### ISSUE TITLE
feat-teacher-and-student-exam-api

### ISSUE THREAD

**Issue by junslog** [BeeLinkers/EngleBee#30]
### ✨ 구현할 기능

-  시험 출제, 시험 풀기, 시험 피드백, 시험 상세정보 관련 API 및 뷰에 담을 model 생성 기능을 개발합니다.

- 시험이 생성 상태일 때 ( `CREATED` ), 선생님에게 보여질 페이지(`exam-register.html`)에 담길 데이터를 model에 담고,
선생님이 시험을 출제할 때 사용할 API를 구현합니다.

- 시험이 준비 상태일 때 ( `PREPARED` ) 선생님 멤버에게 보여줄 데이터를 model에 담는 기능을 구현합니다.

- 시험이 준비 상태일 때 ( `PREPARED` ), 학생에게 보여질 페이지(`exam-solve.html`)에 담길 데이터를 model에 담고,
학생이 시험을 풀 때 사용할 API를 구현합니다.

- 시험이 제출 상태일 때 ( `SUBMITTED` ), 선생님에게 보여질 페이지(`exam-feedback.html`)에 담길 데이터를 model에 담고,
선생님이 시험에 대한 피드백을 할 때 사용할 API를 구현합니다.

- 시험이 제출 상태일 때 ( `SUBMITTED` ), 학생에게 보여질 페이지(`exam-detail.html`)에 담길 데이터를 model에 담는 기능을 구현합니다.

- 시험이 피드백 완료 상태일 때 ( `FEEDBACK_COMPLETED` ), 선생님에게 보여질 페이지(`exam-detail.html`)에 담길 데이터를 model에 담는 기능을 구현합니다.

- 시험이 피드백 완료 상태일 때 ( `FEEDBACK_COMPLETED` ), 학생에게 보여질 페이지(`exam-detail.html`)에 담길 데이터를 model에 담는 기능을 구현합니다.

### ✅ TODO

# **(exam-register.html - @Controller)**
### **( `TeacherExamPageController`,  `TeacherExamPageService` )**

- [x] 처음 렌더링될 때, ( `로그인 세션`, `해당 Exam의 seq`, `List<Exam과 연결된 Lecture의 SubjectLevel>` / `List<Student와 연결된 SubjectLevel>` )이 model에 담겨 전달되도록 하는 기능 구현
  - [x] 해당 Exam이 선생님의 것이 맞는지 확인하여 예외처리하는 기능 구현 ( `ExamRepository` )

# **(exam-register.html - @RestController)**
### **( `TeacherExamApiController` , `TeacherExamService` )**

- [x]  선생님 시험 등록 API 구현 
  - [x] `로그인 세션`, examSeq, List<( String direction, List<String> choices, Integer answer,  String intent )> DTO 
( List<TeacherQuestionCreateRequestDTO> ) 를 컨트롤러에서 입력받도록 구현
    - [x] 입력값에 대한 검증 기능 구현 ( choices의 길이 | answer의 값 범위 | direction과 intent의 길이 )
  - [x] 시험 등록 기능을 하는 서비스 메서드 구현
    - [x] 해당 Exam이 선생님의 것이 맞는지 확인하여 예외처리하는 기능 구현 ( `ExamRepository` )
    - [x] (TX) 해당 Exam의 상태가 `CREATED`이 맞는지 확인하고 이에 대한 예외처리를 하는 기능 구현 ( `ExamRepository` )
    - [x] (TX) Exam의 상태를  `PREPARED`로 변경
    - [x] (TX) `List<TeacherQuestionCreateRequestDTO>`로부터 `List<TeacherQuestion>`으로 변환하여 저장
  - [x] `ResponseEntity<Void>`와 HttpStatus 코드를 통해 API 호출 결과 전달

# **(exam-solve.html - @Controller)**
### **( `StudentExamPageController` , `StudentExamPageService` )**

- [x] 처음 렌더링될 때, ( `로그인 세션`, `해당 Exam의 seq`, `List<TeacherQuestionForStudentToSolveResponseDTO>` : List< Long teacherQuestionSeq, String direction, List<String> choices> )이 페이지에 model에 담겨 전달하도록 하는 기능 구현
  - [x] 해당 Exam이 학생의 것이 맞는지 확인하여 예외처리하는 기능 구현 ( `ExamRepository` )

# **(exam-solve.html - @RestController)**
### **( `StudentExamApiController` , `StudentExamApiService` )**

- [x] 학생 시험 풀기 API 구현
  - [x] examSeq, List<Long teacherQuestionSeq, Integer studentAnswer> DTO를 컨트롤러에서 입력받도록 구현
    - [x] 입력값에 대한 검증 기능 구현 ( studentAnswer의 범위 )
  - [x] 시험 풀기 기능을 하는 서비스 메서드 구현
    - [x] (TX) 해당 Exam의 상태가 `PREPARED`이 맞는지 확인하고 이에 대한 예외처리를 하는 기능 구현
    - [x] (TX) Exam의 상태를 `SUBMITTED`로 변경
    - [x] (TX) `List<StudentQuestionSolveRequestDTO>`를 통해 `TeacherQuestion`의 `insertStudentAnswer` 메서드 호출 ( 학생 답 기입 )
 - [x]  `ResponseEntity<Void>`와 HttpStatus 코드를 통해 API 호출 결과 전달

# **(exam-feedback.html - @Controller)**
### **( `TeacherExamPageController` , `TeacherExamPageService` )**

- [x] 처음 렌더링될 때, ( `로그인 세션`, `해당 Exam의 seq`, `List<SolvedTeacherQuestionResponseDTO>` : List< String direction, List<String> choices>, Integer correctAnswer, Integer studentAnswer, String intent )이 페이지에 model에 담겨 전달하도록 하는 기능 구현
  - [x] 해당 Exam의 상태가 `SUBMITTED`인지 확인하여 예외처리하는 기능 구현 ( `ExamRepository` )
  - [x] 해당 Exam이 선생님의 것이 맞는지 확인하여 예외처리하는 기능 구현 ( `ExamRepository` )

# **(exam-feedback.html - @RestController)**
### **( `TeacherExamApiController` , `TeacherExamApiService` )**

- [x] 선생님 시험 피드백하기 API 구현
  - [x] examSeq, feedback, List< String subjectName, String subjectLevel > DTO를 컨트롤러에서 입력받도록 구현
    - [x] 입력값에 대한 검증 기능 구현 ( studentAnswer의 범위 )
  - [x] 시험 피드백하기 기능을 하는 서비스 메서드 구현
    - [x] (TX) 해당 Exam의 상태가 `SUBMITTED`이 맞는지 확인하고 이에 대한 예외처리를 하는 기능 구현
    - [x] (TX) 해당 `subjectName`이 유효한 코드인지, `subjectLevel`은 유효한 코드인지 확인하고 예외처리하는 기능 구현
    - [x] (TX) Exam의 상태를 `FEEDBACK_COMPLETED`로 변경
    - [x] (TX) `feedback`을 통해 Exam에 `addTeacherFeedback` 메서드 호출
    - [x] (TX) `List<StudentSubjectLevelRequestDTO>`를 통해 학생의 과목 레벨 변경 ( 선생님이 학생 레벨 평가 )
 - [x]  `ResponseEntity<Void>`와 HttpStatus 코드를 통해 API 호출 결과 전달

# **(exam-detail.html - @Controller)**
### **( `GeneralExamPageController` , `GeneralExamPageService` )**

- [x] 아래 case 1~3이 아닌 요청에 대해서 예외처리합니다.

case 1) exam의 상태가 `PREPARED`이고, 요청한 멤버가 '선생님' 멤버일 때

- [x] 처음 렌더링 될 때, `examSeq`와 `examTitle`, `List< Long teacherQuestionSeq, String direction, List<String> choices, Integer correctAnswer, String intent >` 를 전달하여 확인할 수 있도록 합니다.
- [x] 페이지에 따로 API 기능은 없고, 읽기 전용으로만 페이지 렌더링합니다.

case 2) exam의 상태가 `SUBMITTED`이고, 요청한 멤버가 '학생' 멤버일 때

- [x] 처음 렌더링 될 때, `examSeq`와 `examTitle`, `List< Long teacherQuestionSeq, String direction, List<String> choices, Integer correctAnswer, Integer studentAnswer, String intent >` 를 전달하여 확인할 수 있도록 합니다.
- [x] 페이지에 따로 API 기능은 없고, 읽기 전용으로만 페이지 렌더링합니다.

case 3) exam의 상태가 `FEEDBACK_COMPLETED`일 때

- [x] 처음 렌더링 될 때, `examSeq`와 `examTitle`, `List< Long teacherQuestionSeq, String direction, List<String> choices, Integer correctAnswer, Integer studentAnswer, String intent >`, `feedback` 를 전달하여 확인할 수 있도록 합니다.
- [x] 페이지에 따로 API 기능은 없고, 읽기 전용으로만 페이지 렌더링합니다.
