### ISSUE TITLE
refactor-student-main-api

### ISSUE THREAD

**Issue by yeong1203** [BeeLinkers/EngleBee#31]
### ✨ 리팩토링할 기능

- Q&A 리스트 조회 기능이 제외됩니다.
- 수업 여부에 따른 데이터가 다릅니다.
- 풀어야 할 시험 리스트 최신글 기준으로 최대 5개까지 보여지고, 페이지네이션 제외됩니다.
- 제출한 시험 리스트가 최신글 기준으로 최대 5개까지 보여지고, 페이지네이션 제외됩니다.
- 수정된 코드에 맞는 Test Code 작성하기

### ✅ TODO

- [x] Q&A 리스트 관련 기능 삭제
- [x] 수업 여부에 따른 데이터 조회
- [x] 풀어야 할 시험 리스트 최신글 기준으로 5개 조회 구현
- [x] 제출한 시험 리스트 최신글 기준으로 5개 조회 구현
- [x] 수정된 코드에 맞도록 Test Code 작성
