### ISSUE TITLE
refactor-teacher-main-api

### ISSUE THREAD

**Issue by yeong1203** [BeeLinkers/EngleBee#33]
### ✨ 리팩토링할 기능

- Q&A 리스트 조회 기능이 제외됩니다.
- 수업 상태에 따른 데이터 조회 
- 출제해야 할 시험 리스트 최신글 기준으로 최대 5개까지 보여지고, 페이지네이션 제외됩니다.
- 출제한 시험 리스트가 최신글 기준으로 최대 5개까지 보여지고, 페이지네이션 제외됩니다.
- 수정된 코드에 맞는 Test Code 작성하기

### ✅ TODO

- [x]  Q&A 리스트 관련 기능 삭제
- [x] 수업 상태에 따른 데이터 조회 기능 수정
- [x] 출제해야할 시험 리스트 조회 기능 수정
- [x] 출제한 시험 리스트 조회 기능 수정
- [x] 수정한 코드에 맞는 테스트 코드 작성
