### ISSUE TITLE
refactor-general-admin-test

### ISSUE THREAD

**Issue by ram9611** [BeeLinkers/EngleBee#40]
### ✨ 리팩토링할 기능

- 화상채팅 및 관리자 기능 관련 Controller, Service 미비된 테스트 코드 작성

### ✅ TODO

- [ ] AdminApiController 테스트 코드 작성
- [ ] AdminService 테스트 코드 작성
- [ ] ChatApiController 테스트 코드 작성
