### ISSUE TITLE
feat-teacher-exam-recommendation-api

### ISSUE THREAD

**Issue by junslog** [BeeLinkers/EngleBee#44]
### ✨ 구현할 기능

- (exam-register.html) 선생님이 시험 등록 페이지에서 학생의 레벨과 수업 레벨을 기반으로 선정된 시험 문제들을 기반으로 문제를 추천받을 수 있습니다.
- (exam-feedback.html) 선생님이 시험 피드백 페이지에서 (시험 문제 - 선생님의 답 - 학생의 답 - 출제의도)를 기반으로 피드백 내용을 추천받을 수 있습니다.

### ✅ TODO

- [x] OpenAI API Key를 발급받습니다.
- [x] API Key를 통해 API에 대한 CallTest를 진행합니다.
- [x] Open AI와 연동할 의존성을 설치합니다, 혹은 WebClient를 통해 직접 통신합니다.
- [x] 간단한 ThymeLeaf 텍스트 박스 뷰와 ChatGPT API를 연동해서 비동기 방식으로 데이터를 받을 수 있는지를 테스트합니다.
- [x] 테스트가 성공적으로 끝나면, 시험 문제 추천 API를 구현합니다.
  - [x] 클라이언트에서 넘겨준 학생 과목 레벨 수준 / 강의 과목 레벨 수준을 통해 프롬프트를 작성합니다.
  - [x] API Key와 프롬프트를 통해 ChatGPT에 요청을 보내고 응답을 수신합니다.
  - [x] 이를 `SseEmitter`를 사용하여 비동기 방식으로 한 글자씩 보내줍니다.
- [x] 시험 문제 추천 시 GPT에게 넘겨줄 프롬프트를 설계 및 작성합니다.
  - [x] `exam-register.html` 에서, 학생의 과목레벨과 강의의 과목레벨을 서버에 보내서, 그에 맞는`TeacherQuestion`을 약 5개 뽑아옵니다. 
  - [x] `TeacherQuestion`을 적절한 포맷으로 변경하여 인풋 토큰 ( GPT에 보낼 메시지 )에 추가합니다.
  - [x] GPT에게 받아온 데이터를 `SseEmitter`를 통해 한글자씩 보내줍니다.
  - [x] 이 때, 커스터마이징해서 등록한 `ThreadPoolTaskExecutor`과 `@Asnyc`를 사용하여 Tomcat의 메인 쓰레드 풀 작업의 부하를 분산합니다.
  - [x] 클라이언트 (타임리프) 에서 Promise 를 이용해 한글자씩 뷰에 렌더링해줍니다.
  - [x] 이 때, 동시에 여러번 요청하면 응답이 꼬일 수 있으니, 추천하기 버튼을 누르면 버튼이 비활성화 되고, `[englebee-end]` 메시지가 오면  2초 뒤에 버튼을 활성화 시킵니다.
  - [x] 이외의 시험 등록 페이지와 뷰 연동 작업을 완료합니다.
