### ISSUE TITLE
feat-view-template-add-and-route

### ISSUE THREAD

**Issue by junslog** [BeeLinkers/EngleBee#49]
### ✨ 구현할 기능

- ThymeLeaf 기반으로 작업했던 뷰를 프로젝트에 추가합니다.

- 기존 페이지 컨트롤러의 주소에 알맞게 라우팅 처리합니다.

### ✅ TODO

- [x] ThymeLeaf 템플릿 뷰를 프로젝트에 추가하기
- [x] 기존에 사용하던 뷰(JSP 페이지, 임시용 ThymeLeaf 페이지) 제거
- [x] 타임리프 뷰가 적절히 라우팅되도록 기존 컨트롤러와 매핑
