### ISSUE TITLE
feat-jpa-mapping-db

### ISSUE THREAD

**Issue by junslog** [BeeLinkers/EngleBee#5]
### ✨ 구현할 기능

- 현재 JPA 세팅에서 엔티티 생성이 불가능하므로, 생성 관련 Builder 혹은 정적 팩토리 메서드 작성

- 엔티티의 외래키를 업데이트 하기 위한 메서드 추가 ( 단방향 및 양방향 )

### ✅ TODO

- [x] 각 Entity별 생성 메서드를 작성 ( Builder or 정적 팩토리 메서드 사용 )

- [x] Enum의 이름 값 입력 시 해당하는 Enum으로 출력하는 정적 팩토리 메서드 작성

  - [x] 해당 정적 팩토리 메서드에서 예외 발생 시 throw 할 Custom Exception 생성

  - [x] 해당하는 Custom Exception을 처리해줄 `@ExceptionHandler` 및 `@RestControllerAdvice` 작성

- [x] 단방향 연관관계를 가진 엔티티들의 외래 키 등록/수정을 위한 메서드 작성

- [x] (양방향 연관관계) `Question`과 `Reply`의 양방향 연관관계에서 외래 키 등록/수정을 위한 연관관계 편의 메서드 작성

- [x] (양방향 연관관계) `Exam`과 `TeacherQuestion`의 양방향 연관관계에서 외래 키 등록/수정을 위한 연관관계 편의 메서드 작성
