### ISSUE TITLE
feat-infra-cicd-setting

### ISSUE THREAD

**Issue by junslog** [BeeLinkers/EngleBee#7]
### ✨ 구현할 기능

- 스프링 부트에 대한 `Dockerfile`을 작성하여 이미지로 빌드할 수 있도록 합니다.
- `develop`브랜치로 푸시할 때 도커 이미지를 빌드하고, 도커 허브로 푸시하는 CI 파이프라인을 구축합니다.
- 도커 허브로 부터 스프링 부트 이미지를 EC2에 받아와 컨테이너로 실행하는 CD 파이프라인을 구축합니다.
- EC2에 Nginx를 설치하고 이를 통해서만 Spring Boot 서버로 접근할 수 있도록 설정합니다.
- AWS RDS에 MariaDB를 설치하고, DDL을 통해 테이블 생성 후 테스트 데이터를 넣습니다.
- Nginx 서버와 도커 컨테이너 상의 Spring Boot 서버 그리고 RDS 상의 MariaDB 서버를 연결합니다.
- Certbot을 통해 Nginx 서버에 HTTPS 를 적용합니다. ( HTTP로 접근 시 HTTPS 로 리다이렉트하는 설정을 포함합니다. )
- 개발 환경의 Profile과 (local), 운영 환경의 Profile, 테스트 환경의 Profile을 분리합니다.

### ✅ TODO

- [x] EngleBee 스프링부트 서버에 대한 Dockerfile을 작성합니다.
- [x] MariaDB에 우리 DB 매핑 정보를 담은 DDL 및 테스트 데이터용 DML을 담은 파일을 작성합니다.
- [x] MaraiDB를 AWS RDS에 배포합니다.
- [x] Github Repository - Settings > Secrets 에 도커 허브에 접근할 수 있는 토큰 및 유저아이디 값, AWS 접근 관련 secret값을 지정합니다.
- [x] Github Actions를 활용하여 CI/CD 파이프라인을 구축합니다.
  - [x] CI Pipeline에서 SpringBoot 도커 이미지를 빌드하고, Docker Hub Repository에 푸시합니다.
  - [x] CD Pipeline에서 AWS EC2에 SSH를 통해 연결하여 도커 컨테이너를 배포합니다.
- [x] Nginx 서버와 SpringBoot 서버에 탄력적 IP를 붙이고, NginX 서버가 외부에서 접근 가능한지, SpringBoot 서버가 외부에서 접근 불가능한지 테스트합니다.
- [x] Nginx 서버에 도메인을 할당하여, 도메인 이름으로 외부 접근이 가능한지 테스트합니다.
- [x] Nginx 서버에 SSL 인증서를 적용하여 HTTPS 로 요청을 받도록 처리합니다.
- [x] 개발 환경의 Profile과 (local), 운영 환경의 Profile, 테스트 환경의 Profile을 분리합니다.
