### ISSUE TITLE
feat-student-exam-view

### ISSUE THREAD

**Issue by ram9611** [BeeLinkers/EngleBee#73]
### ✨ 구현할 기능

- 학생 멤버는 문제 풀기 페이지에서 할당된 문제를 확인할 수 있습니다.
- 문제를 풀고 제출할 수 있습니다

### ✅ TODO

- [x] 컨트롤러에서 model에 담은 값들을 뷰에서 보여주기
- [x] 선택지를 클릭하면 omr 표시가 되고 다른 선택지를 고르면 원래대로 돌아옵니다
- [x] 제출하기 버튼을 누르면 문제에 대한 answer들이 제출되고 메인 페이지로 돌아옵니다
